package certs

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// registryConfigManager implements the RegistryConfigManager interface
type registryConfigManager struct {
	config             TrustStoreConfig
	registryConfigPath string
	insecureRegistries []string
}

// newRegistryConfigManager creates a new registry configuration manager
func newRegistryConfigManager(config TrustStoreConfig) RegistryConfigManager {
	configDir := filepath.Dir(config.BaseDir)
	registryConfigPath := filepath.Join(configDir, "registries.conf")

	mgr := &registryConfigManager{
		config:             config,
		registryConfigPath: registryConfigPath,
		insecureRegistries: make([]string, 0),
	}

	// Load existing configuration
	mgr.LoadConfig()

	return mgr
}

// UpdateInsecureRegistry updates the insecure registry configuration
func (r *registryConfigManager) UpdateInsecureRegistry(registry string, insecure bool) error {
	// Remove registry from the list first
	r.removeFromInsecureList(registry)

	// Add to list if insecure is true
	if insecure {
		r.insecureRegistries = append(r.insecureRegistries, registry)
	}

	// Save the updated configuration
	return r.SaveConfig()
}

// GetInsecureRegistries returns a list of registries configured as insecure
func (r *registryConfigManager) GetInsecureRegistries() ([]string, error) {
	// Make a copy to prevent external modification
	result := make([]string, len(r.insecureRegistries))
	copy(result, r.insecureRegistries)
	return result, nil
}

// LoadConfig loads the registry configuration from disk
func (r *registryConfigManager) LoadConfig() error {
	// Check if config file exists
	if _, err := os.Stat(r.registryConfigPath); os.IsNotExist(err) {
		// No existing config, start with empty list
		r.insecureRegistries = make([]string, 0)
		return nil
	}

	data, err := os.ReadFile(r.registryConfigPath)
	if err != nil {
		return fmt.Errorf("failed to read registry config: %w", err)
	}

	// Parse the configuration file
	r.insecureRegistries = r.parseInsecureRegistries(string(data))

	return nil
}

// SaveConfig saves the registry configuration to disk
func (r *registryConfigManager) SaveConfig() error {
	// Create config directory if it doesn't exist
	configDir := filepath.Dir(r.registryConfigPath)
	if err := os.MkdirAll(configDir, r.config.DirPermissions); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Generate configuration content
	content := r.generateRegistryConfig()

	// Write configuration using atomic operation
	tempPath := r.registryConfigPath + ".tmp"
	if err := os.WriteFile(tempPath, []byte(content), r.config.FilePermissions); err != nil {
		return fmt.Errorf("failed to write registry config to temp file: %w", err)
	}

	if err := os.Rename(tempPath, r.registryConfigPath); err != nil {
		os.Remove(tempPath) // Clean up temp file
		return fmt.Errorf("failed to move registry config to final location: %w", err)
	}

	return nil
}

// removeFromInsecureList removes a registry from the insecure registries list
func (r *registryConfigManager) removeFromInsecureList(registry string) {
	for i, reg := range r.insecureRegistries {
		if reg == registry {
			// Remove element at index i
			r.insecureRegistries = append(r.insecureRegistries[:i], r.insecureRegistries[i+1:]...)
			return
		}
	}
}

// parseInsecureRegistries parses insecure registries from configuration content
func (r *registryConfigManager) parseInsecureRegistries(content string) []string {
	var insecureRegs []string
	lines := strings.Split(content, "\n")

	inRegistriesBlock := false
	for _, line := range lines {
		line = strings.TrimSpace(line)

		// Look for [registries.insecure] section
		if strings.Contains(line, "[registries.insecure]") {
			inRegistriesBlock = true
			continue
		}

		// If we're in another section, stop parsing
		if strings.HasPrefix(line, "[") && inRegistriesBlock {
			break
		}

		// Parse registries line if we're in the right section
		if inRegistriesBlock && strings.HasPrefix(line, "registries") {
			// Extract registry list from 'registries = ["reg1", "reg2"]'
			start := strings.Index(line, "[")
			end := strings.Index(line, "]")
			if start >= 0 && end > start {
				regList := line[start+1 : end]
				registries := strings.Split(regList, ",")
				for _, reg := range registries {
					reg = strings.Trim(strings.TrimSpace(reg), `"'`)
					if reg != "" {
						insecureRegs = append(insecureRegs, reg)
					}
				}
			}
		}
	}

	return insecureRegs
}

// generateRegistryConfig generates the registry configuration content
func (r *registryConfigManager) generateRegistryConfig() string {
	var content strings.Builder

	content.WriteString("# Registry configuration for buildah/podman\n")
	content.WriteString("# Generated by idpbuilder-oci trust store manager\n\n")

	if len(r.insecureRegistries) > 0 {
		content.WriteString("[registries.insecure]\n")
		content.WriteString("registries = [")

		for i, registry := range r.insecureRegistries {
			if i > 0 {
				content.WriteString(", ")
			}
			content.WriteString(fmt.Sprintf(`"%s"`, registry))
		}

		content.WriteString("]\n\n")
	}

	content.WriteString("# Trust store certificates are stored in:\n")
	content.WriteString(fmt.Sprintf("# %s/<registry>/\n", r.config.BaseDir))

	return content.String()
}
