#!/usr/bin/env bash
# State transition: REVIEW_WAVE_INTEGRATION → REVIEW_WAVE_ARCHITECTURE
# Generated by: state-manager
# Date: 2025-11-02T23:57:51Z
# Iteration: 7
# Reason: Wave 2.2 iteration 7 code review found 0 bugs - proceeding to architecture review

set -euo pipefail

TIMESTAMP=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

echo "📝 Updating orchestrator-state-v3.json..."
jq --arg ts "$TIMESTAMP" '
  .state_machine.current_state = "REVIEW_WAVE_ARCHITECTURE" |
  .state_machine.previous_state = "REVIEW_WAVE_INTEGRATION" |
  .state_machine.last_transition_timestamp = $ts |
  .state_machine.last_state_manager_consultation = {
    "timestamp": $ts,
    "consultation_type": "SHUTDOWN_CONSULTATION",
    "from_state": "REVIEW_WAVE_INTEGRATION",
    "to_state": "REVIEW_WAVE_ARCHITECTURE",
    "validated": true,
    "validation_result": "APPROVED",
    "validated_by": "state-manager",
    "transition_allowed": true,
    "guard_condition": "bugs_found == 0",
    "guard_satisfied": true,
    "work_completed": {
      "code_review_complete": true,
      "bugs_found": 0,
      "build_status": "SUCCESS",
      "test_status": "PASS",
      "test_count": 27,
      "coverage": "89.6%",
      "integration_quality": "EXCELLENT",
      "r359_compliance": "VERIFIED"
    },
    "exit_criteria_met": true,
    "entry_criteria_met": true
  } |
  .state_machine.state_history += [{
    "from_state": "REVIEW_WAVE_INTEGRATION",
    "to_state": "REVIEW_WAVE_ARCHITECTURE",
    "timestamp": $ts,
    "validated_by": "state-manager",
    "reason": "Wave 2.2 Iteration 7: Code review complete with 0 bugs found, build and tests passing. Proceeding to architecture review per guard condition (bugs_found == 0).",
    "phase": 2,
    "wave": 2,
    "iteration": 7,
    "orchestrator_proposal": "REVIEW_WAVE_ARCHITECTURE",
    "proposal_accepted": true,
    "consultation_type": "SHUTDOWN_CONSULTATION",
    "guard_condition_satisfied": true,
    "validation_checks": {
      "transition_allowed": true,
      "from_state_exists": true,
      "to_state_exists": true,
      "in_allowed_transitions": true,
      "guard_condition_met": true,
      "bugs_found": 0,
      "build_status": "SUCCESS",
      "test_status": "PASS",
      "r359_compliance": "VERIFIED",
      "r288_compliance": true,
      "r517_compliance": true,
      "state_machine_compliance": "VERIFIED"
    }
  }]
' orchestrator-state-v3.json > orchestrator-state-v3.json.tmp && mv orchestrator-state-v3.json.tmp orchestrator-state-v3.json

echo "✅ orchestrator-state-v3.json updated"

echo "📝 Updating integration-containers.json..."
jq --arg ts "$TIMESTAMP" '
  (.wave_integrations[] | select(.container_id == "wave-phase2-wave2")) |= (
    .iteration_history += [{
      "iteration": 7,
      "started_at": "2025-11-02T18:50:08Z",
      "completed_at": $ts,
      "review_report": "efforts/phase2/wave2/integration-workspace/.software-factory/phase2/wave2/integration/CODE-REVIEW-REPORT--20251102-235751.md",
      "bugs_found": 0,
      "bugs_fixed": 0,
      "bug_ids": [],
      "status": "APPROVED",
      "reviewer": "code-reviewer",
      "review_timestamp": $ts,
      "decision": "APPROVED",
      "blocking_bugs": [],
      "notes": "Wave 2.2 Iteration 7: Code review complete with 0 bugs. Build SUCCESS, tests PASS (27/27, 89.6% coverage), 0 conflicts. Integration quality EXCELLENT. Proceeding to architecture review.",
      "build_status": "SUCCESS",
      "test_status": "PASS",
      "test_count": 27,
      "coverage": "89.6%",
      "integration_quality": "EXCELLENT",
      "r359_verified": true
    }]
  ) |
  .metadata.last_updated = $ts |
  .metadata.notes = "State transition: REVIEW_WAVE_INTEGRATION to REVIEW_WAVE_ARCHITECTURE (iteration 7)" |
  .metadata.state_transition = "REVIEW_WAVE_ARCHITECTURE" |
  .metadata.updated_by = "state-manager" |
  .state_machine_sync.current_state = "REVIEW_WAVE_ARCHITECTURE" |
  .state_machine_sync.previous_state = "REVIEW_WAVE_INTEGRATION" |
  .state_machine_sync.last_transition = $ts |
  .state_machine_sync.last_sync = $ts |
  .current_state = "REVIEW_WAVE_ARCHITECTURE" |
  .last_updated_by = "state-manager"
' integration-containers.json > integration-containers.json.tmp && mv integration-containers.json.tmp integration-containers.json

echo "✅ integration-containers.json updated"

echo "📝 Updating bug-tracking.json (no new bugs)..."
jq --arg ts "$TIMESTAMP" '
  .metadata.last_updated = $ts |
  .metadata.notes = "State transition: REVIEW_WAVE_INTEGRATION to REVIEW_WAVE_ARCHITECTURE (iteration 7)" |
  .metadata.state_transition = "REVIEW_WAVE_ARCHITECTURE" |
  .metadata.updated_by = "state-manager" |
  .state_machine_sync.current_state = "REVIEW_WAVE_ARCHITECTURE" |
  .state_machine_sync.previous_state = "REVIEW_WAVE_INTEGRATION" |
  .state_machine_sync.last_transition = $ts |
  .state_machine_sync.last_sync = $ts |
  .current_state = "REVIEW_WAVE_ARCHITECTURE" |
  .last_updated_by = "state-manager"
' bug-tracking.json > bug-tracking.json.tmp && mv bug-tracking.json.tmp bug-tracking.json

echo "✅ bug-tracking.json updated"

# fix-cascade-state.json only updated if it exists
if [ -f fix-cascade-state.json ]; then
    echo "📝 Updating fix-cascade-state.json..."
    jq --arg ts "$TIMESTAMP" '
      .metadata.last_updated = $ts |
      .metadata.notes = "State transition: REVIEW_WAVE_INTEGRATION to REVIEW_WAVE_ARCHITECTURE (iteration 7)" |
      .current_state = "REVIEW_WAVE_ARCHITECTURE" |
      .last_updated_by = "state-manager"
    ' fix-cascade-state.json > fix-cascade-state.json.tmp && mv fix-cascade-state.json.tmp fix-cascade-state.json
    echo "✅ fix-cascade-state.json updated"
else
    echo "⏩ fix-cascade-state.json does not exist, skipping"
fi

echo ""
echo "✅ All state files updated successfully"
