name: Validate No Deprecated Rules

on:
  pull_request:
    paths:
      - 'agent-states/**'
      - '.claude/**'
      - 'rule-library/**'
  push:
    branches:
      - main
      - develop
    paths:
      - 'agent-states/**'
      - '.claude/**'
      - 'rule-library/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run deprecated rule validation
      run: |
        chmod +x utilities/validate-no-deprecated-rules.sh
        ./utilities/validate-no-deprecated-rules.sh
      
    - name: Report failure
      if: failure()
      run: |
        echo "❌ Deprecated rule references detected!"
        echo "Please update all deprecated rule references before merging."
        echo ""
        echo "Replacement guide:"
        echo "  - R236, R237 → R290"
        echo "  - R252, R253 → R288"
        echo "  - R187, R188, R189, R190 → R287"
        exit 1